name: Coverage

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: dependencies
          key: coverage-dependencies-20210420

      - name: Install dependencies
        run: sudo bash script/build.sh

      - name: Configure
        run: |
          cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=Debug \
          -DKEPUB_BUILD_TEST=ON -DKEPUB_BUILD_COVERAGE=ON
        env:
          CC: gcc
          CXX: g++

      - name: Build
        run: cmake --build build --config Debug -j"$(nproc)" --target coverage

      # https://github.com/coverallsapp/github-action
      - name: Coveralls
        if: ${{ matrix.compiler.cxx == 'g++' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build/test/unit_test/lcov.info
