name: Release

on:
  release:
    # https://stackoverflow.com/questions/59319281/github-action-different-between-release-created-and-published
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kaiserlancelot/kenv:latest
      options: --cap-add SYS_ADMIN --device /dev/fuse --security-opt apparmor:unconfined

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: bash script/build.sh

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release -j"$(nproc)"

      - name: CPack
        run: sudo cpack
        working-directory: build

      - name: Install
        run: |
          sudo dpkg -i kepub*.deb
          sudo ldconfig
        working-directory: build

      - name: Run executable
        run: kepub -v

      # https://github.com/softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/kepub*.deb
            build/kepub*.tar.gz
