name: Sanitizer

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kaiserlancelot/kenv:latest
      options: --cap-add SYS_ADMIN --device /dev/fuse --security-opt apparmor:unconfined
    strategy:
      matrix:
        # https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html
        build_type: ["Debug", "Release", "RelWithDebInfo", "MinSizeRel"]
        compiler:
          - { cc: "gcc", cxx: "g++" }
          - { cc: "clang", cxx: "clang++" }

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: bash script/build.sh

      - name: Configure
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DKEPUB_BUILD_TEST=ON -DKEPUB_SANITIZER=ON
        env:
          CC: ${{ matrix.compiler.cc }}
          CXX: ${{ matrix.compiler.cxx }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} -j"$(nproc)"

      - name: Test
        run: ctest -C ${{ matrix.build_type }} -j1 --output-on-failure
        working-directory: build
        env:
          # FIXME fmt odr-violation
          ASAN_OPTIONS: detect_odr_violation=0
